services:
    frontend:
      build:
        context: ./frontend
      ports:
        - "4200:80"
      depends_on:
        - backend

    backend:
      build:
        context: ./backend
      ports:
        - "5001:80"